version: "3"

services:
  basic:
    image: mclearning2/pc:basic
    build:
      context: .
      dockerfile: Dockerfile
      args:
          USER: ${USER}
          HOME: ${HOME}
    container_name: devel-basic
    tty: true
    stdin_open: true
    network_mode: "host"
    env_file: 
        - .env
    volumes:
        - ~/.ssh:/home/${USER}/.ssh:ro
