version: "3"

services:
  basic:
    image: mclearning2/pc:basic
    build:
      context: .
      dockerfile: Dockerfile
      args:
          USER: ${USER}
          HOME: ${HOME}

    tty: true
    stdin_open: true

    container_name: devel-basic
    command: /bin/zsh
    env_file: 
        - .env
    volumes:
        - ~/.ssh:/home/${USER}/.ssh:ro
